version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"  # Expor a porta do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data: